### ISSUE TITLE
Tools=>pptext Alpha sort not yet implemented

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts-py#310] opened 2024-06-26 18:56 UTC
Tools=>pptxt, I can't discern a difference between Sort: Line & Col and Alpha/Type.  Something seems to have happened but it still seems sorted by Line & Col.

**Comment by G4OEU** [comment] 2024-06-29 10:28
I'm away from my computer until 12 July. Will follow up on this on my return.

**Comment by G4OEU** [comment] 2024-07-16 15:49
Alpha sort is working as expected. It sorts strictly on the highlighted character/string on a line, maintaining the ordering by file lines when the same highlighted character/string occurs on more than one line. You can see how it is working if you try it on a simple file made up of the following four lines:

“My ain wee wee Nellie!”
Both agreed they had had a grand time.
for sayin’ that that shouldna hae been left out
A few of his elders and friends had had little meetings on the subject

These lines will appear in the "Repeated words check" section near the top of the PPTXT report. Switch between "Line & Col" sort and "Alpha/Type" sort to see how the report changes.

I would like to close this issue if there are no further comments.

**Comment by windymilla** [comment] 2024-07-16 16:06
Thanks @G4OEU - I confirmed that I could see a difference with Alpha sorting. Each category of error is still self contained, but within the category, errors are sorted alphabetically based on the highlighted string, or sorted by line/col, depending on the dialog setting. Since @okrick also agrees, I'm happy for this to be closed.
Are you able to close it @G4OEU or @okrick? If not, then I can.

**Closed** 2024-07-16 16:09 UTC
